### ISSUE TITLE
Error: Scene Ballexample, WebSocket closed with Reason

### ISSUE THREAD

**Issue by AdityaSher** [BrandlMax/BCI-BrainFuck#2]
This error popped up after I configured the ballexample.cs by adding headset and app details.
Steps to re-create: 
1) Connect EPOC+ using USB
2) Open EmotivBCI and connect headset
3) Load Example in Unity
4) Play Scene

Error Log: 
WebSocket closed with reason: An exception has occurred while connecting.
UnityEngine.Debug:Log(Object)
BrainFuck:_close(Object, CloseEventArgs) (at Assets/BrainFuck/BrainFuck.cs:182)
WebSocketSharp.Ext:Emit(EventHandler`1, Object, CloseEventArgs) (at Assets/BrainFuck/websocket-sharp/Ext.cs:1080)
WebSocketSharp.WebSocket:close(CloseEventArgs, Boolean, Boolean) (at Assets/BrainFuck/websocket-sharp/WebSocket.cs:676)
WebSocketSharp.WebSocket:processException(Exception, String) (at Assets/BrainFuck/websocket-sharp/WebSocket.cs:1000)
WebSocketSharp.WebSocket:connect() (at Assets/BrainFuck/websocket-sharp/WebSocket.cs:787)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()

**Comment by BrandlMax** [comment]
Hello Aditya,
In your mail, you asked the question:

> "Why is the port no 54321 (and URL emotivecortex.com instead of localhost:6868)"

So I'm guessing you changed the address?
EPOC does not connect directly to Unity, i.e. not via a local network, but via Bluetooth with the CortexUI app and then sends the data via this app to the EMOTIV servers. There the prediction takes place and the answer is then transmitted to Unity via the WebSocket (wss://emotivcortex.com:54321).

You can read the details here:
https://emotiv.github.io/cortex-docs/#introduction 

From your steps above, I see a few other potential sources of error:
1. My emotive requires you to connect via Bluetooth, not USB. Maybe that's the case with yours, too?
2. for the connection to Unity, via the Emotiv servers, you need the CortexUI app, not the EmotivBCI app. 

It seems that in order to download the CortexUI app you have to register for basic API access now: https://www.emotiv.com/developer/

I hope this helps you and gives you a few approaches to solving the problem 🙈
Max

**Comment by AdityaSher** [comment]
@Brandlmax

I changed the address back to the default.

I have the developer access, and I have tested all the commands using websocket.org/echo.html

I connected using Bluetooth now.

The EmotivApp is also connected to my device, and I have already approved my cortex App.

I am still facing the error as above, please guide me. :(

**Comment by AdityaSher** [comment]
> Hello Aditya,
> In your mail, you asked the question:
> 
> > "Why is the port no 54321 (and URL emotivecortex.com instead of localhost:6868)"
> 
> So I'm guessing you changed the address?
> EPOC does not connect directly to Unity, i.e. not via a local network, but via Bluetooth with the CortexUI app and then sends the data via this app to the EMOTIV servers. There the prediction takes place and the answer is then transmitted to Unity via the WebSocket (wss://emotivcortex.com:54321).

Please check this commit out regarding this thing:
https://github.com/Emotiv/cortex-v2-example/commit/c48861a01e4ebe5f17fe0e46f921214700463386

**Comment by BrandlMax** [comment]
Hi Aditya,
it looks like Emotiv is currently changing its API, or released a V2 (https://emotiv.gitbook.io/cortex-api/). My code is based on the V1 API (https://emotiv.github.io/cortex-docs/). 

V1 still seems to be online,  but it looks like only with the old version of the CortexUI App. The next weeks I have to finish another project, I hope that I will be able to update to V2 during the semester break.

I hope you can use one of the V2 examples in the meantime (https://github.com/Emotiv/cortex-v2-example)

Sorry,
Max

**Comment by AdityaSher** [comment]
Ok thanks for the help :) 

Hope you are able to complete your project, all the best :)

**Comment by BrandlMax** [comment]
I've rewritten BrainFramework for Unity for the V2 API:
[https://github.com/BrandlMax/BrainFramework](https://github.com/BrandlMax/BrainFramework)

Let me know if this works for you, 
Max
